### ISSUE TITLE
Math Driver

### ISSUE THREAD

**Issue by KonstaMF** [DataTables/Editor-NET#7]
https://github.com/KonstaMF/Math-Driver-Extend
Hello, is it possible to implement this in code for a Windows system or .NET Framework ? I need to help.

**Comment by AllanJard** [comment]
How does this relate to DataTables Editor?

**Comment by KonstaMF** [comment]
I thought it had to do with knowledge of the
.NET Framework and .NET Core, and perhaps knowledge of their editing capabilities or library editing tools.

**Comment by AllanJard** [comment]
The Math Driver? I'm afraid this isn't a general programming support forum. SO would be better for general .NET questions.

**Comment by KonstaMF** [comment]
I have formulas that I need to present in the form of code, an example of use - the work of the operating system or the work of applications based on this idea. My programming skills are not sufficient yet, so I am looking for someone to help me implement the project, someone who would also be interested.

**Comment by AllanJard** [comment]
Thanks for the clarification. If you need a programmer, you'd be better looking for a freelancer on UpWork or similar. I'm afraid I'm not a contractor for hire.

**Comment by KonstaMF** [comment]
Thanks, I'll try my luck there, it's just that I've contacted freelancers, but found no help.
