### ISSUE TITLE
License file for .NET Library

### ISSUE THREAD

**Issue by jqnatividad** [DataTables/Editor-NET#9]
Hi @AllanJard !

First off, thanks for DataTables and deciding to open source it and the server-side libraries!

However, I can't seem to find a License file detailing the license used by the server-side libraries.

Can you please point me where it is?

Thanks!
cc @tomecirun @tino097

**Comment by AllanJard** [comment]
Excellent point - sorry I missed that. The server-side libraries for Editor / DataTables are MIT licensed and [I've just added a License.txt file](https://github.com/DataTables/Editor-NET/commit/c5d0f2817b3b271827505d31d1237afd4fc175a5) to reflect that.
